### ISSUE TITLE
issue #2 User Can Turn Their Car

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] add data model for cars current position
- [x] add css transform: rotate
- [x] add keydown event listener
- [x] if key is arrow change className to rule with transform
- [x] test and fix an errors
