### ISSUE TITLE
issue #3 User Can Start Their Car

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add location to data model
- [x] add absolute positioning to car
- [x] if keydown target is space 
- [x] add setInterval every 16ms
- [x] use style property to update top and left styles for car
- [x] test and fix any errors
