### ISSUE TITLE
issue #4 User Can Stop Their Car

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add started to data model
- [x] if keydown is space
- [x] check if started is true or false
- [x] if started is true clear interval
- [x] test and fix any errors
