### ISSUE TITLE
Issue #5 User Can Steer Their Car

### ISSUE THREAD

**Issue by katiefugate** [katiefugate/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] check data model for car position
- [x] change style to rotate based on current position
- [x] test and fix any errors
